apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkit-config
  namespace: default
data:
  buildkitd.toml: |
    [registry."registry.default.svc.cluster.local:5000"]
      http = true
      insecure = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkitd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
      - name: buildkitd
        image: moby/buildkit:v0.17.3
        args:
        - --addr
        - unix:///run/buildkit/buildkitd.sock
        - --addr
        - tcp://0.0.0.0:1234
        - --config
        - /etc/buildkit/buildkitd.toml
        securityContext:
          privileged: true
        volumeMounts:
        - name: buildkit-socket
          mountPath: /run/buildkit
        - name: buildkit-config
          mountPath: /etc/buildkit
        ports:
        - containerPort: 1234
      volumes:
      - name: buildkit-socket
        emptyDir: {}
      - name: buildkit-config
        configMap:
          name: buildkit-config
---
apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 1234
    targetPort: 1234
  selector:
    app: buildkitd
